### ISSUE TITLE
Error Processing Plans Involving CNAME Records

### ISSUE THREAD

**Issue by terraflubb** [ClouDNS/octodns_cloudns#4]
Thank you very much for the plugin, it's nice having something first-party to use in our OctoDNS setup.

We're having a problem when making changes involving CNAME records. It might involve other records types without a `#values` property,  but I've only hit it with CNAME.

Here is the error trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/octodns/cmds/sync.py", line 62, in main
    manager.sync(
  File "/usr/local/lib/python3.8/site-packages/octodns/manager.py", line 856, in sync
    total_changes += target.apply(plan)
  File "/usr/local/lib/python3.8/site-packages/octodns/provider/base.py", line 2[98](https://github.com/nedap/stpst-dns/actions/runs/10420151627/job/28859610653#step:7:99), in apply
    self._apply(plan)
  File "/usr/local/lib/python3.8/site-packages/octodns_cloudns/__init__.py", line 692, in _apply
    getattr(self, f"_apply_{class_name.lower()}")(change)
  File "/usr/local/lib/python3.8/site-packages/octodns_cloudns/__init__.py", line 658, in _apply_delete
    record_ids = self.records_are_same(existing)
  File "/usr/local/lib/python3.8/site-packages/octodns_cloudns/__init__.py", line 583, in records_are_same
    for value in existing.values:
AttributeError: 'CnameRecord' object has no attribute 'values'
```

This error stems from how OctoDNS `CnameRecords` are using the `ValueMixin` as opposed to the `ValuesMixin` (or something else that provides `.values`) since it can only ever have a single value. So it gets `.value`.

In your `#records_are_same` function, it's assuming that everything has a `#values`, [here](https://github.com/ClouDNS/octodns_cloudns/blob/main/octodns_cloudns/__init__.py#L583).

I'm guessing the solution would be to just make sure `values` exists before going down that branch? I'm afraid I don't fully appreciate what's going on in `#record_are_same` to weigh in with a PR. I'd guess it's either skip it, or refactor that chunk of logic so it can be executed on a single `.value` if that's what the record has?

Please let me know if I can be of assistance sorting this out.

**Comment by terraflubb** [comment]
This is still an issue, is this repository monitored or should we create issues through CloudNS's normal support channels?

I see @Venkoul99 is the primary contributor... can I draw your attention to this?

**Comment by boyanpeychev** [comment]
Hi, I'm afraid @Venkoul99 is no longer contributing to this project.
To organize everything, can you please share with me if you have this issue only with CNAME records or with other too? Like ALIAS?

**Comment by terraflubb** [comment]
Thanks for weighing in!

We've only experienced it with CNAME records but we aren't making use of ALIAS. The errors being thrown are only on CNAME cases.

It seems unusual that we'd be experiencing this while nobody else has. I'll take a look at our records in CloudNS to see if maybe there's some weird state in there which is causing the plugin to become confused.

**Comment by terraflubb** [comment]
It seems like the problem is that the `records_are_same` is called all the time when there is a `_delete` invoked, and that method is needed when dealing with any record capable of having multiple values.

Here's the method: https://github.com/ClouDNS/octodns_cloudns/blob/main/octodns_cloudns/__init__.py#L579

But since it _always_ uses it, there's an assumption that every record will respond to `.values` in it, so it fails when it hits a `CNAME` which is a record that can only have a single value.

I tried to gently hack around it, by instead passing a list containing the single `[value]`, but all that did was replace the crash with it silently failing to remove the record :grin:, which makes sense because there's nothing within the loop there to consider anything besides the ones with multiple values.

I'm curious if other people are having the same experience, as it seems like it wouldn't take much to hit this particular case.

**Comment by boyanpeychev** [comment]
Can you please provide me some details for the source of the records. As per our tests there are no issues with the sync of the records from one ClouDNS into another, but probably if the source provider is having some extra values for the CNAME records it is possible that to cause the issues?

**Comment by terraflubb** [comment]
Thanks for looking into this! We've updated it over here, and some of the issues are resolved! We no longer get that crash.

I am observing a bit of a new issue related to CNAME records though. I'm not sure how to create a test case in order for you to verify this... but here's the situation:

Before:
```yaml
'test-place':
  - type: CNAME
    value: banana.test.com.
```

`test-place.test.com` currently is set up as a CNAME to `banana.test.com`, this is both in our YAML source and I also verified it by checking out the ClouDNS admin.

We want to change it to a series of A records:

```yaml
'test-place:
  - ttl: 3600
    type: A
    values:
      - 1.2.3.4
      - 1.2.3.5
      - 1.2.3.6
      - 1.2.3.7
```

When OctoDNS is run, it does determine this is what needs to happen:

```
********************************************************************************
* test.com.
********************************************************************************
* cloudns (ClouDNSProvider)
*   Delete <CnameRecord CNAME 86400, test-place.test.com., banana.test.com.>
*   Create <ARecord A 3600, test-place.test.com., ['1.2.3.4', '1.2.3.5', '1.2.3.6', '1.2.3.7']> (config)
```

And it reports that it does however many deletes / creates, but they don't actually happen. In this case, I had to make the changes by hand in the admin.

Could it still be having trouble deleting the record?

For this particular case, I changed the config by hand in the ClouDNS admin, but I can try to set up this situation again on another one of our domains and increase logging to `DEBUG` to see I can see what's happening with the ClouDNS API calls.

**Comment by terraflubb** [comment]
When trying to debug this, I found an issue with how the plugin emits log files. Here's a fix for that which I am currently using:

https://github.com/ClouDNS/octodns_cloudns/pull/6

**Comment by terraflubb** [comment]
So I was able to reproduce my problem. It looks like the plugin still has trouble deleting things. Even _without_ the `CNAME` to `A` setup, other records which the plugin were aware of, and have a delete as part of the plan, survive the OctoDNS run.

Here are some logs I tried to scrub:

In the OctoDNS plan, where the current state is having a few CNAMEs which I just want deleted, and also one which is "changing" from a CNAME to an A record (I know that's not an update, but a destroy/create).

```
cloudns (ClouDNSProvider)
  Delete <CnameRecord CNAME 3600, apple.test.com., foo.something-else.com.>
  Delete <CnameRecord CNAME 3600, banana.test.com., foo2.something-else.com.>
  Delete <CnameRecord CNAME 3600, flubb.test.com., banana2.test.com.>
  Create <ARecord A 3600, flubb.test.com., ['1.2.3.4', '1.2.3.5']> (config)
```

Then in the log output (see my PR above to see the branch needed to get this out).

Unfortunately, I think the thing which was censoring the auth credentials in the output might have also pruned away the rest of the parameters used in the API. But the interesting stuff is in the file itself. In the whole run it never even tries to do anything than `get-zone-info` or `add-record`.

Usually this would fail silently, but when the delete has to run in order for the A records to be created, it causes an error, which is what we see here:

```
[139929606151040] DEBUG ClouDNSProvider[cloudns] _apply: zone=test.com., len(changes)=8
[139929606151040] DEBUG ClouDNSProvider[cloudns] Request URL: https://api.cloudns.net/dns/get-zone-info.json?auth-id=***&auth-***
[139929606151040] DEBUG ClouDNSProvider[cloudns] Request Response: {"name":"test.com","type":"master","zone":"domain","status":"1"}
[139929606151040] DEBUG ClouDNSProvider[cloudns] Request URL: https://api.cloudns.net/dns/add-record.json?auth-id=***&auth-***
[139929606151040] DEBUG ClouDNSProvider[cloudns] Request Response: {"status":"Failed","statusDescription":"This host is already taken by your CNAME record."}
[139929606151040] DEBUG ClouDNSProvider[cloudns] Request URL: https://api.cloudns.net/dns/add-record.json?auth-id=***&auth-***
[139929606151040] DEBUG ClouDNSProvider[cloudns] Request Response: {"status":"Failed","statusDescription":"This host is already taken by your CNAME record."}
```

So there seems to be something still a bit wrong with the code that decides what to delete, because I think this illustrates that it never ends up generating a request.
